algoritmo "casoImparouPar"
// Função : Descobrir c o numero e impar ou par com estrutura caso
// Autor :  Caic Henriques Rodrigues
// Data : 23/07/2020
// Seção de Declarações 
var
numero: inteiro

inicio
// Seção de Comandos 

escreval("Digite um número qualquer numero: ")
leia(numero)

Caso 1
 se (numero mod 2)= 0 entao
   escreval (" - Esse numero e par")

     senao
Caso 2
   escreval (" - Esse numero é impar")

  

fimse


    



fimalgoritmo
