algoritmo "imparoupar"
// Função : Solicite um de informe se ele e impar ou par
// Autor : Caic Henriques Rodrigues
// Data : 09/06/2020
// Seção de Declarações 
var
numero: inteiro

inicio

escreval("Digite o seu numero:")
leia(numero)

se numero mod 2 = 0 entao
 escreval ("O número",numero," é par!")
  senao
      escreval("O número ",numero," é impar!")
      fimse




// Seção de Comandos 
fimalgoritmo
