algoritmo "valordesaque"
// Função : Solicite o valor saque e informe o saldo
// Autor : Caic Henriques Rodrigues
// Data : 10/06/2020
// Seção de Declarações 
var


 saldo,valor,saque:real

inicio
// entrada

 saldo <- 3500


 escreval("Qual o valor do saque? ")
 leia(saque)


//precessamento

valor <- (saldo-saque)

//saida

escreval ("Seu saldo atual é de :",valor)



fimalgoritmo
